eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: localhost
    port: 8080
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      healthcheck:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  zipkin:
    base-url: http://localhost:8891
  boot:
    admin:
      client:
        url: http://localhost:8889
        instance:
          service-base-url: http://localhost:8889
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
        password: ${spring.security.user.name}
        username: ${spring.security.user.password}
  security:
    user:
      name: "admin"
      password: "admin"